FROM nginx
COPY ["/static/index.html", "/usr/share/nginx/html/static/index.html"]
COPY ["/static/chat.html", "/usr/share/nginx/html/static/chat.html"]
COPY ["nginx.conf", "/etc/nginx/nginx.conf"]
EXPOSE 80
